import { Fira_Code as FiraCode } from "next/font/google";


import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";

// Import the Fira Code font
const firaCodeFont = FiraCode({
  subsets: ["latin"],
  variable: "--font-fira-code", // Optional for using CSS variables
});

// Metadata for the page
export const metadata = {
  title: "Ali Blog",
  description: "Generated by Ali Blog",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${firaCodeFont.variable} antialiased`}>
          <Provider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {/* Main Content */}
                {children}
            </ThemeProvider>
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}